#!/usr/bin/env bash

usage="Usage: $(basename "$0") [-h | --help]

Returns the positional command line arguments that are present in stdin. The
options are extracted using the regex provided by the CLI_OPTIONS_REGEX
environment variable. If the regex is not provided, then the default regex is
used.

where:
    options:
    -h --help   shows this help messages"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h | --help)
                echo "$usage"
                exit 0
                ;;
            *)
                echo "Unknown argument: $1"
                echo "$usage"
                exit 1
                ;;
        esac
        shift
    done
}

parse_args "$@"
rg --only-matching --line-number --replace '$1' -- "^\s*(-{1,2}[a-zA-Z0-9\-_=]+)"
